version: '3'

services:
  front:
    build:
      context: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/front:cached
      - front_node_modules:/front/node_modules
    tty: true
    stdin_open: true
    command: yarn dev
  server:
    build: ./server
    ports:
      - 8888:8888
    volumes:
      - ./server:/api
volumes: 
  front_node_modules: